name: Format code
on:
  push:
  pull_request:

env:
  FILE_PATTERN: .go
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Format code
        run: goimports -w .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format code
          commit_options: "--no-verify --signoff"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          file_pattern: ${{ env.FILE_PATTERN }}
