name: Format code
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FILE_PATTERN: .go
jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17"
      - run: go version
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Format code
        run: goimports -w .
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply Code formatter changes"
