name: Format code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Format code
        run: goimports -w .
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "fuyafuya1224@gmail.com"
          git commit -a -m "Auto-format code"
          git push origin HEAD:${{ github.head_ref }}
